### ISSUE TITLE
Please don't be shy :)

### ISSUE THREAD

**Issue by ShamoX** [zverok/geo_coord#3]
I understand that first version for computer scientists (as myself) could begin at 0.0.0 (why then using 0.0.1, did you fix a bug ? ^^) but it's a little frightening to see a gem at a version of 0.0. I usually say nothing, but your effort inspire me to make some contributions, and I want to start by a cheer and lets say that you achieved all the first features you wanted to include in your gem and so it could be called 1.0 :)

**Comment by zverok** [comment]
Well, my logic is simple: to achieve at least 0.1.0, gem should go through some real "battle-testing" (e.g. being used in some complicated projects, which probably will identify problems in API and/or bugs). Unfortunately, I can't say it about `Geo::Coord`: the project I've designed it for is moving slowly, and I haven't heard of anybody else using it. ¯\\\_(ツ)_/¯

Maybe even second public release could be numbered 0.1.0, but first one definitely should start from the very beginning, as any decent new gem do.

**Comment by ShamoX** [comment]
Yeah, we definitely don't agree on that, but that's your gem.
Thanks for the clarification :-)
