### ISSUE TITLE
Comparing Coordinate Precision

### ISSUE THREAD

**Issue by Hengjie** [zverok/geo_coord#7]
Thanks for making the gem! One thing I'm trying to accomplish is comparing the precision of the coordinates from different sources, and picking the most precise one. 

For example, `source_1_lng: 36.001` should be more precise than `source_2_lng: 36.0`. Is there an easy way to calculate the precision from this gem?

Thanks

**Comment by zverok** [comment]
It is an interesting question, but probably not directly related to geo coordinates. If you definitely know the two numbers are the same latitude just with different precision (and only in this case), just comparing fractional parts would be enough, probably:

```ruby
g1 = Geo::Coord.parse('36.001,0')
# => #<Geo::Coord 36°0'4"N 0°0'0"W> 
g2 = Geo::Coord.parse('36.0,0')
# => #<Geo::Coord 36°0'0"N 0°0'0"W> 
g1.lat.frac.abs
# => 0.1e-2 
g2.lat.frac.abs
# => 0.0 
```
The first number is higher, therefore, the precision is higher. But if you have, say, "36.001" and "36.1", this method would not work. Probably your best guess would be just rendering them to text (or only their fractional parts) and just count digits.

```ruby
g1.lat.frac.to_s('F') # 'F' says to render in "humane" format
# => "0.001" 
g2.lat.frac.to_s('F')
# => "0.0" 
```
...the first has more chars, therefore more digits, therefore cand be considered more "precise".

But the particular answer really depends on the task.

**Comment by Hengjie** [comment]
Thanks! I'll take a look into it and post a solution once it's production ready :)
